#!/bin/bash

declare -a options=(" Fix Touchpad
 Pulse Audio
 Calibrate Touch to Click
 Config Bash Prompt ")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'Run Fixing Script: ')

    if [ "$choice" == ' Fix Touchpad ' ]; then
        exec ~/.scripts/fixit/fixScroll
    fi
    if [ "$choice" == ' Pulse Audio ' ]; then
        exec gedit ~/.scripts/fixit/resetPulseAudio
    fi
    if [ "$choice" == ' Calibrate Touch to Click ' ]; then
        exec gedit ~/.scripts/fixit/calibrateTouchpad
    fi
    if [ "$choice" == ' Config Bash Prompt ' ]; then
        exec ~/.scripts/appearance/bashTest
    fi
